[build]
command = "sed -i \"s|CROSSWAY_ESV_API_KEY|${CROSSWAY_ESV_API_KEY}|g\" netlify.toml && yarn build"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/esv/*"
  to = "https://api.esv.org/:splat"
  status = 200
  force = true
  headers = {Authorization = "CROSSWAY_ESV_API_KEY", Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
