backend:
  name: github
  repo: christchurchmayfair/bible-overview
  use_graphql: true
media_folder: "images/uploads"
collections:
  - name: study
    label: Study
    folder: "content/studies"
    create: true
    format: json
    slug: "{{slug}}"
    fields:
      - { label: "Index", name: "index", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Icon", name: "icon", widget: "select", options: ["analytics", "globe", "alert", "ribbon", "hand-left", "book", "warning", "shield-checkmark", "refresh", "crown", "trending-up", "construct", "flame", "moon", "exit", "heart-circle", "paw", "person", "cross", "sunny", "hourglass", "checkmark-done", "cloud", "home"] }
      - { label: "Overview", name: "overview", widget: "text" }
      - { label: "Themes", name: "themes", widget: "list" }
      - { label: "Patterns", name: "patterns", widget: "list" }
      - { label: "Promises", name: "promises", widget: "list" }
      - { label: "Progressions", name: "progressions", widget: "list" }
      - { label: "Key Application", name: "keyApplication", widget: "text" }
      - { label: "Prayer Points", name: "prayerPoints", widget: "list" }
      - label: "Questions"
        name: "questions"
        widget: "object"
        fields:
          - { label: "Section", name: "section", widget: "string" }
          - label: "Questions List"
            name: "questions"
            widget: "list"
            field: { label: "Question", name: "question", widget: "string" }
          - label: "Answers"
            name: "answers"
            widget: "list"
            required: false
            field: { label: "Answer", name: "answer", widget: "string" }
      - label: "Timeline"
        name: "timeline"
        widget: "list"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Details", name: "details", widget: "text" }
          - { label: "Type", name: "type", widget: "select", options: ["Event", "Period"] }
          - { label: "SubType", name: "subType", widget: "select", options: ["Major", "Minor"], required: false }
          - { label: "Date", name: "date", widget: "number", required: false }
          - { label: "Duration", name: "duration", widget: "string", required: false }
      - { label: "Leaders Notes", name: "leadersNotes", widget: "text", required: false }
      - label: "Additional Resources"
        name: "additionalResources"
        widget: "list"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Type", name: "type", widget: "select", options: ["video", "audio", "article", "book"] }